workflows:
  android-workflow:
    name: Build Android APK
    max_build_duration: 15
    environment:
      node: 20.11.1
    scripts:
      - npm install
      - npx cap sync android
      - cd android && ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
